title: "RESEARCH.ME"
author: "Ke3rNel"
description: "Feel Free to contact me : t.me/Ke3rNel"

# Contact Information
# email: ""
github_username: "Binary-win"
Telegram_Channel: "@SecNote"
# linkedin_username: ""

# Optional: Uncomment and populate the following fields for additional social media links
# twitter_username: "twitteruser"
# facebook_username: "username"
# flickr_username: "username"
# instagram_username: "username"
# pinterest_username: "username"
# youtube_username: "username"
# googleplus_username: "+username"

#########################################################################################
######### Configuration below this point should only be modified if you're familiar #######
######### with the Jekyll and plugin settings. Otherwise, leave it as-is. ##################
#########################################################################################

theme: "minima"  # Minimalistic theme for simplicity and clarity

# Optional: Enable RSS feed generation
# rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true  # Disable syntax highlighting to enhance performance and compatibility with certain formats

# Plugins to extend Jekyll functionality
plugins:
  - jekyll-feed  # Enables automatic RSS feed generation
  - jekyll-sitemap  # Generates a sitemap.xml for better SEO and search engine discoverability

# Title generation configuration for posts
titles_from_headings:
  strip_title: true  # Strips unnecessary prefixes from headings in titles
  collections: true  # Ensures collection posts also have correctly generated titles

# Default values for posts
defaults:
  - scope:
      path: ""
      type: post  # Default type for content is set to "post"
    values:
      tags: [Other]  # Default tag for new posts is "Other"
